//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskBoeking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boekingen
    {
        public int BoekingId { get; set; }
        public int UserId { get; set; }
        public int DeskId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Desk Desk { get; set; }
        public virtual User User { get; set; }
    }
}
