//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskBoeking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeskBoekingEntities : DbContext
    {
        public DeskBoekingEntities()
            : base("name=DeskBoekingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boekingen> Boekingens { get; set; }
        public virtual DbSet<Desk> Desks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
